version: '3.8'

services:
  greenbin:
    image: ghcr.io/dishabh13/greenbin-app:v1.2
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: greenbin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: